CREATE TABLE `DATACENTER` (
  `DATACENTER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DATACENTER_NAME` varchar(32) NOT NULL,
  PRIMARY KEY (`DATACENTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `ENVIRONMENT` ADD FK_DATACENTER_ID bigint(20);

ALTER TABLE `ENVIRONMENT` ADD FOREIGN KEY (`FK_DATACENTER_ID`) REFERENCES `DATACENTER` (`DATACENTER_ID`);